### ISSUE TITLE
Improvement: provide a syntax to merge arrays

### ISSUE THREAD

**Issue by asgoth** [kevin-smets/caml#5]
Sometimes it is needed to merge arrays, e.g. when you want to expand a default list of types.

Maybe the following syntax could be used:

```
files:
  +: *baseFiles
  - "path/to/file1"
  - "path/to/file2"
```

**Comment by kevin-smets** [comment]
Damn, I thought I replied to this issue, but clearly that is not the case. This is under consideration for now. I would like to leave the yaml syntax intact but that might be impossible in this case. It would indeed be a useful feature.

**Comment by kevin-smets** [comment]
Is the following sufficient for your use case?

```
arr: &arr
  - 'one'
  - 'two'

yarr:
  <<: *arr
  - 'three'
```

Output:

```
{
  "arr": [
    "one",
    "two"
  ],
  "yarr": [
    "one",
    "two",
    "three"
  ]
}
```

It does not appear to work with [] syntax. More examples can be found @ http://stackoverflow.com/questions/9254178/is-there-yaml-syntax-for-sharing-part-of-a-list-or-map

**Comment by asgoth** [comment]
Cool ;)
